###
GET http://localhost:3000/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1zcm9uYXlvMDVAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MTA1MjQ0MzEsImV4cCI6MTcxMDYxMDgzMX0.bqIOWssJlDhXPcFqjrTNf5sekKiNYpqSPvDFBmGkgCI

###
GET http://localhost:3000/users/id HTTP/1.1
Content-Type: application/json


###
POST http://localhost:3000/auth/register HTTP/1.1
Content-Type: application/json

{
  "username":"maicol",
  "email":"msronayo05@gmail.com",
  "password":"password",
}
###
PATCH http://localhost:3000/auth/register HTTP/1.1
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1zcm9uYXlvMDVAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MTA1MjQ0MzEsImV4cCI6MTcxMDYxMDgzMX0.bqIOWssJlDhXPcFqjrTNf5sekKiNYpqSPvDFBmGkgCI

{
  "username":"maicol",
  "email":"msronayo05@gmail.com",
  "password":"password",
  "role":"admin"
}
###
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
  "email":"msronayo03@gmail.com",
  "password":"password"
}
